# DBT image for BigQuery
FROM python:3.11-slim
WORKDIR /app

# Copy
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copie du projet dbt
COPY . /app

# Entrypoint qui va générer ~/.dbt/profiles.yml
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Par défaut on lance dbt via l'entrypoint 
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["dbt", "run"]
